[package]
name = "hitokoto-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
num_cpus = "1.16.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
