[package]
name = "hitokoto-rust"
version = "0.2.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
clap = { version = "4.5.32", features = ["derive"] }
num_cpus = "1.16.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.6", features = ["mysql", "runtime-tokio-native-tls"] }
