name: Rust Release Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C lto=fat"  # 启用LTO和CPU优化

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ contains(matrix.target, 'windows') && 'windows-latest' || 'ubuntu-latest' }}
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      
      # 安装 musl-tools (仅 musl 目标需要)
      - name: Install musl-tools
        if: contains(matrix.target, 'musl') && runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      
      # 安装 gcc-aarch64-linux-gnu 用于 ARM 交叉编译
      - name: Install ARM cross-compilation tools
        if: contains(matrix.target, 'aarch64') && runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
        
      - name: Install musl ARM cross-compilation tools
        if: contains(matrix.target, 'aarch64') && runner.os == 'Linux' && contains(matrix.target, 'musl')
        uses: lmq8267/dl-musl@25-02-05
        
      # 安装 Rust stable 工具链
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: rust-src  # 为LTO提供必要组件
      
      # 缓存优化
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # 为 ARM 目标设置链接器
      - name: Set linker for ARM targets
        if: contains(matrix.target, 'aarch64')
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc" >> $GITHUB_ENV
      
      # 构建步骤
      - name: Build Release
        run: |
          cargo build --target ${{ matrix.target }} --release --all-features --config profile.release.lto=true --config profile.release.codegen-units=1
          ls target/${{ matrix.target }}/release/
      
      # 二进制优化 (Linux)
      - name: Strip binaries (Linux)
        if: contains(matrix.target, 'linux') && runner.os == 'Linux'
        run: |
          strip target/${{ matrix.target }}/release/hitokoto-rust
      
      # 上传制品
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/hitokoto-rust*
            target/${{ matrix.target }}/release/*.exe
            !target/${{ matrix.target }}/release/*.d
            !target/${{ matrix.target }}/release/*.pdb
          if-no-files-found: error