name: Publish Docker Image on Release

on:
  release:
    types: [published] # 当 Release 发布时触发

env:
  # Docker 镜像的名称，通常是你的 Docker Hub 用户名/组织名加上仓库名
  IMAGE_NAME: moyanjdc1/hitokoto-rust

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read # 允许 checkout 代码

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}} # 例如：v1.0.0 -> 1.0.0
            type=semver,pattern={{major}}.{{minor}} # 例如：v1.0.0 -> 1.0
            type=semver,pattern={{major}} # 例如：v1.0.0 -> 1
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) || github.event_name == 'release' }} # release 时也打 latest 标签
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ github.date }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
